/**
 * Generates `design/components.json` — the resolved visual spec a design tool
 * needs to rebuild Arlo UI components as Figma component sets.
 *
 * Why this renders instead of reading the source: a component's appearance is
 * tokens *plus* variant logic *plus* overrides, and only the last of those is
 * invisible from outside. `Button size="lg"` resolves its label from
 * `typography.title3` (17/22.1) — not the `buttonLarge` scale you would guess —
 * then overrides the weight to 600. Any exporter that reasons about tokens
 * rather than executing the component gets that wrong, silently.
 *
 * So each cell of the variant matrix is really rendered, through the real
 * ThemeProvider, and the resulting tree is serialised with styles already
 * flattened. What lands in the JSON is what the component actually produces.
 *
 * It lives as a test because that is what already has the React Native
 * transform wired up; the assertions are a smoke check, the artifact is the
 * point. `npm run design:components` runs just this file.
 *
 * Not captured — and not capturable on a canvas: motion (springs, press
 * feedback, transitions) and gesture behaviour. Those are recorded as prose in
 * `notes`, for an agent to carry across rather than draw.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { render } from '@testing-library/react-native';
import { StyleSheet } from 'react-native';
import { ThemeProvider } from '../../src/foundation/theme-provider';
import { MATRIX, type Axis } from './matrix';

/**
 * Render with the colour scheme pinned.
 *
 * `ThemeProvider` defaults to `'system'`, and its resolver is
 * `system === 'light' ? 'light' : 'dark'` — so a null scheme (which is what
 * `Appearance.getColorScheme()` returns under Jest) silently resolves to dark.
 * An export that relied on the ambient value would emit dark-mode colours
 * labelled as nothing at all.
 */
const renderIn = (scheme: 'light' | 'dark', ui: React.ReactElement) =>
  render(ui, {
    wrapper: ({ children }) => <ThemeProvider defaultName={scheme}>{children}</ThemeProvider>,
  });

const OUT = resolve(__dirname, '../../../../design/components.json');

const GENERATED =
  'AUTO-GENERATED by packages/registry/test/design-export. Do not edit by hand. ' +
  'Regenerate with `npm run design:components`.';

/** Style keys that describe appearance on a canvas. Everything else is noise. */
const KEEP = new Set([
  'width', 'height', 'minHeight', 'minWidth', 'maxHeight', 'maxWidth',
  'margin', 'marginTop', 'marginBottom', 'marginLeft', 'marginRight',
  'marginHorizontal', 'marginVertical',
  'padding', 'paddingTop', 'paddingBottom', 'paddingLeft', 'paddingRight',
  'paddingHorizontal', 'paddingVertical',
  'flexDirection', 'alignItems', 'justifyContent', 'flex', 'flexGrow',
  'flexShrink', 'flexWrap', 'gap', 'rowGap', 'columnGap', 'alignSelf',
  'position', 'top', 'bottom', 'left', 'right', 'zIndex',
  'backgroundColor', 'opacity', 'overflow',
  'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius',
  'borderBottomLeftRadius', 'borderBottomRightRadius',
  'borderWidth', 'borderTopWidth', 'borderBottomWidth', 'borderLeftWidth',
  'borderRightWidth', 'borderColor',
  'color', 'fontSize', 'fontWeight', 'fontFamily', 'lineHeight',
  'letterSpacing', 'textAlign', 'textTransform',
  'shadowColor', 'shadowOffset', 'shadowOpacity', 'shadowRadius', 'elevation',
]);

type Node = {
  type: string;
  style?: Record<string, unknown>;
  text?: string;
  children?: Node[];
};

/** Flatten RN's style arrays and drop keys that mean nothing on a canvas. */
function resolveStyle(style: unknown): Record<string, unknown> | undefined {
  const flat = StyleSheet.flatten(style as never) as Record<string, unknown> | undefined;
  if (!flat) return undefined;
  const out: Record<string, unknown> = {};
  for (const key of Object.keys(flat).sort()) {
    if (!KEEP.has(key)) continue;
    const value = flat[key];
    if (value === undefined || value === null) continue;
    // Animated values serialise as objects; take the current numeric value so
    // the export records the resting state rather than an animation handle.
    if (typeof value === 'object' && value !== null && '_value' in (value as object)) {
      out[key] = (value as { _value: unknown })._value;
      continue;
    }
    out[key] = value;
  }
  return Object.keys(out).length ? out : undefined;
}

function serialise(json: unknown): Node | null {
  if (json == null || typeof json === 'boolean') return null;
  if (typeof json === 'string' || typeof json === 'number') {
    return { type: 'text', text: String(json) };
  }
  const el = json as { type: string; props?: Record<string, unknown>; children?: unknown[] };
  if (!el.type) return null;

  const kids = (el.children ?? [])
    .map(serialise)
    .filter((n): n is Node => n !== null);

  // Collapse a Text whose only child is a string into a single node.
  if (kids.length === 1 && kids[0].type === 'text' && !kids[0].children) {
    return {
      type: el.type,
      style: resolveStyle(el.props?.style),
      text: kids[0].text,
    };
  }

  const node: Node = { type: el.type, style: resolveStyle(el.props?.style) };
  if (kids.length) node.children = kids;
  return node;
}

/** Cartesian product of the axes, as Figma-facing and code-facing prop maps. */
function combinations(axes: Axis[]): Array<{
  variant: Record<string, string>;
  props: Record<string, unknown>;
}> {
  let acc: Array<{ variant: Record<string, string>; props: Record<string, unknown> }> = [
    { variant: {}, props: {} },
  ];
  for (const axis of axes) {
    const next: typeof acc = [];
    for (const row of acc) {
      for (const [figmaValue, codeValue] of Object.entries(axis.values)) {
        next.push({
          variant: { ...row.variant, [axis.property]: figmaValue },
          props: { ...row.props, [axis.prop]: codeValue },
        });
      }
    }
    acc = next;
  }
  return acc;
}

describe('design export', () => {
  it('renders every variant and writes design/components.json', () => {
    const components = MATRIX.map((spec) => {
      const cells = combinations(spec.axes).map(({ variant, props }) => {
        const light = renderIn('light', spec.sample(props));
        const lightTree = serialise(light.toJSON());
        light.unmount();

        const dark = renderIn('dark', spec.sample(props));
        const darkTree = serialise(dark.toJSON());
        dark.unmount();

        return { variant, props, trees: { light: lightTree, dark: darkTree } };
      });

      expect(cells.length).toBeGreaterThan(0);
      for (const cell of cells) {
        expect(cell.trees.light).not.toBeNull();
        expect(cell.trees.dark).not.toBeNull();
        // Both modes are engineered, not derived — if they serialise identically
        // for a component that paints a surface, a theme lookup was missed.
        expect(JSON.stringify(cell.trees.light)).not.toBe(JSON.stringify(cell.trees.dark));
      }

      return {
        component: spec.component,
        set: spec.set,
        axes: spec.axes.map((a) => ({
          property: a.property,
          prop: a.prop,
          values: Object.keys(a.values),
        })),
        notes: spec.note,
        variants: cells,
      };
    });

    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(
      OUT,
      JSON.stringify({ _generated: GENERATED, components }, null, 2) + '\n',
    );

    expect(components.length).toBe(MATRIX.length);
  });
});
