/**
 * Generates `design/components.json` — the resolved visual spec a design tool
 * needs to rebuild Arlo UI components as Figma component sets.
 *
 * Why this renders instead of reading the source: a component's appearance is
 * tokens *plus* variant logic *plus* overrides, and only the last of those is
 * invisible from outside. `Button size="lg"` resolves its label from
 * `typography.title3` (17/22.1) — not the `buttonLarge` scale you would guess —
 * then overrides the weight to 600. Any exporter that reasons about tokens
 * rather than executing the component gets that wrong, silently.
 *
 * Each cell of the variant matrix is really rendered, through the real
 * ThemeProvider, and the tree serialised with styles flattened. Alongside every
 * value sits the token that produced it, so a canvas can *bind* rather than
 * copy — a hardcoded hex is how a design library rots. Colours are observed via
 * a probe render rather than inferred; see `attribution.ts` for why inference
 * is unsound.
 *
 * It lives as a test because that is what already has the React Native
 * transform wired up; the assertions are a smoke check, the artifact is the
 * point. `npm run design:components` runs just this file.
 *
 * Not captured — and not capturable on a canvas: motion (springs, press
 * feedback, transitions) and gesture behaviour. Those are recorded as prose in
 * `notes`, for an agent to carry across rather than draw.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { render } from '@testing-library/react-native';
import { StyleSheet } from 'react-native';
import {
  colorTokenNames,
  makeColorProbe,
  makeNumericProbe,
  type Attribution,
} from './attribution';

// Adds probe themes alongside the real ones. `name` is preserved because
// components branch on `t.name === 'dark'` — change it and the probe tree stops
// matching the real tree structurally, which is the whole basis of the zip.
jest.mock('../../src/foundation/tokens', () => {
  const actual = jest.requireActual('../../src/foundation/tokens');
  const { makeColorProbe: colorProbe, makeNumericProbe: numericProbe } =
    jest.requireActual('./attribution');
  // Colours and numbers are probed in the *same* render: sentinels for colour,
  // sub-pixel epsilons for everything numeric. One extra render per scheme
  // covers spacing, radii, sizing and type as exactly as it covers colour.
  const numeric = numericProbe({
    spacing: actual.spacing,
    radii: actual.radii,
    sizing: actual.sizing,
    typography: actual.typography,
  }).probe;
  const probed = (theme: Record<string, unknown>) => ({
    ...theme,
    colors: colorProbe(theme.colors).probe,
    spacing: numeric.spacing,
    radii: numeric.radii,
    sizing: numeric.sizing,
    typography: numeric.typography,
  });
  return {
    ...actual,
    themes: {
      ...actual.themes,
      probeLight: probed(actual.themes.light),
      probeDark: probed(actual.themes.dark),
    },
  };
});

/* eslint-disable import/first */
import { ThemeProvider } from '../../src/foundation/theme-provider';
import { themes } from '../../src/foundation/tokens';
import { MATRIX, type Axis } from './matrix';

const OUT = resolve(__dirname, '../../../../design/components.json');

const GENERATED =
  'AUTO-GENERATED by packages/registry/test/design-export. Do not edit by hand. ' +
  'Regenerate with `npm run design:components`.';

const actualTokens = jest.requireActual('../../src/foundation/tokens');
const SENTINELS = {
  light: makeColorProbe(actualTokens.themes.light.colors).bySentinel,
  dark: makeColorProbe(actualTokens.themes.dark.colors).bySentinel,
};
const NUMERIC = makeNumericProbe({
  spacing: actualTokens.spacing,
  radii: actualTokens.radii,
  sizing: actualTokens.sizing,
  typography: actualTokens.typography,
}).byProbe;

/** Style keys that describe appearance on a canvas. Everything else is noise. */
const KEEP = new Set([
  'width', 'height', 'minHeight', 'minWidth', 'maxHeight', 'maxWidth',
  'margin', 'marginTop', 'marginBottom', 'marginLeft', 'marginRight',
  'marginHorizontal', 'marginVertical',
  'padding', 'paddingTop', 'paddingBottom', 'paddingLeft', 'paddingRight',
  'paddingHorizontal', 'paddingVertical',
  'flexDirection', 'alignItems', 'justifyContent', 'flex', 'flexGrow',
  'flexShrink', 'flexWrap', 'gap', 'rowGap', 'columnGap', 'alignSelf',
  'position', 'top', 'bottom', 'left', 'right', 'zIndex',
  'backgroundColor', 'opacity', 'overflow',
  'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius',
  'borderBottomLeftRadius', 'borderBottomRightRadius',
  'borderWidth', 'borderTopWidth', 'borderBottomWidth', 'borderLeftWidth',
  'borderRightWidth', 'borderColor',
  // Per-edge colours are separate keys in RN's flattened style; keeping only
  // `borderColor` silently dropped Tabs' underline track colour.
  'borderTopColor', 'borderBottomColor', 'borderLeftColor', 'borderRightColor',
  'color', 'fontSize', 'fontWeight', 'fontFamily', 'lineHeight',
  'letterSpacing', 'textAlign', 'textTransform',
  'shadowColor', 'shadowOffset', 'shadowOpacity', 'shadowRadius', 'elevation',
]);

const isColorKey = (k: string) => /color/i.test(k);

/** Numeric properties a token could legitimately supply. `flex` and `opacity` could not. */
const TOKENISABLE = new Set([
  'padding', 'paddingTop', 'paddingBottom', 'paddingLeft', 'paddingRight',
  'paddingHorizontal', 'paddingVertical',
  'margin', 'marginTop', 'marginBottom', 'marginLeft', 'marginRight',
  'marginHorizontal', 'marginVertical',
  'gap', 'rowGap', 'columnGap',
  'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius',
  'borderBottomLeftRadius', 'borderBottomRightRadius',
  'fontSize', 'lineHeight', 'letterSpacing',
  'width', 'height', 'minWidth', 'minHeight',
]);

type Node = {
  type: string;
  style?: Record<string, unknown>;
  tokens?: Record<string, Attribution>;
  text?: string;
  children?: Node[];
};

function resolveStyle(style: unknown): Record<string, unknown> | undefined {
  const flat = StyleSheet.flatten(style as never) as Record<string, unknown> | undefined;
  if (!flat) return undefined;
  const out: Record<string, unknown> = {};
  for (const key of Object.keys(flat).sort()) {
    if (!KEEP.has(key)) continue;
    const value = flat[key];
    if (value === undefined || value === null) continue;
    if (typeof value === 'object' && value !== null && '_value' in (value as object)) {
      out[key] = (value as { _value: unknown })._value;
      continue;
    }
    out[key] = value;
  }
  return Object.keys(out).length ? out : undefined;
}

function serialise(json: unknown): Node | null {
  if (json == null || typeof json === 'boolean') return null;
  if (typeof json === 'string' || typeof json === 'number') {
    return { type: 'text', text: String(json) };
  }
  const el = json as { type: string; props?: Record<string, unknown>; children?: unknown[] };
  if (!el.type) return null;

  const kids = (el.children ?? []).map(serialise).filter((n): n is Node => n !== null);

  if (kids.length === 1 && kids[0].type === 'text' && !kids[0].children) {
    return { type: el.type, style: resolveStyle(el.props?.style), text: kids[0].text };
  }
  const node: Node = { type: el.type, style: resolveStyle(el.props?.style) };
  if (kids.length) node.children = kids;
  return node;
}

/**
 * Walk the real tree beside its probe twin, attaching the token behind each
 * value. Colours come from the probe (exact); numbers are reverse-mapped by
 * property-scoped scale.
 */
function attribute(real: Node, probe: Node | null, scheme: 'light' | 'dark'): void {
  const style = real.style;
  if (style) {
    const tokens: Record<string, Attribution> = {};
    for (const [key, value] of Object.entries(style)) {
      if (isColorKey(key) && typeof value === 'string') {
        const sentinel = probe?.style?.[key];
        const tokenKey =
          typeof sentinel === 'string'
            ? SENTINELS[scheme].get(sentinel.toUpperCase())
            : undefined;
        if (tokenKey) {
          const names = colorTokenNames(tokenKey);
          if (names) tokens[key] = names;
        } else if (value !== 'transparent') {
          tokens[key] = { hardcoded: true };
        }
      } else if (typeof value === 'number' && TOKENISABLE.has(key)) {
        // The probe tree carries the epsilon-tagged twin of this number. An
        // unperturbed value never came from the theme at all — it is a literal
        // in the component. A perturbed one that matches nothing is arithmetic
        // on a token. Neither is bindable, and both are worth seeing.
        const probed = probe?.style?.[key];
        const hit = typeof probed === 'number' ? NUMERIC.get(probed) : undefined;
        tokens[key] = hit ?? { hardcoded: true };
      }
    }
    if (Object.keys(tokens).length) real.tokens = tokens;
  }
  const rk = real.children ?? [];
  const pk = probe?.children ?? [];
  rk.forEach((child, i) => attribute(child, pk[i] ?? null, scheme));
}

const renderIn = (theme: string, ui: React.ReactElement) =>
  render(ui, {
    wrapper: ({ children }) => (
      <ThemeProvider defaultName={theme as never}>{children}</ThemeProvider>
    ),
  });

function treeFor(scheme: 'light' | 'dark', ui: () => React.ReactElement): Node | null {
  const real = renderIn(scheme, ui());
  const tree = serialise(real.toJSON());
  real.unmount();

  const probed = renderIn(scheme === 'light' ? 'probeLight' : 'probeDark', ui());
  const probeTree = serialise(probed.toJSON());
  probed.unmount();

  if (tree) attribute(tree, probeTree, scheme);
  return tree;
}

function combinations(axes: Axis[]) {
  let acc: Array<{ variant: Record<string, string>; props: Record<string, unknown> }> = [
    { variant: {}, props: {} },
  ];
  for (const axis of axes) {
    const next: typeof acc = [];
    for (const row of acc) {
      for (const [figmaValue, codeValue] of Object.entries(axis.values)) {
        next.push({
          variant: { ...row.variant, [axis.property]: figmaValue },
          props: { ...row.props, [axis.prop]: codeValue },
        });
      }
    }
    acc = next;
  }
  return acc;
}

describe('design export', () => {
  it('exposes probe themes for colour attribution', () => {
    expect(themes).toHaveProperty('probeLight');
    // A probe colour must never collide with a real one, or the zip lies.
    const real = new Set(Object.values(actualTokens.themes.light.colors as Record<string, string>));
    for (const v of Object.values(themes.probeLight.colors as Record<string, string>)) {
      expect(real.has(v)).toBe(false);
    }
  });

  it('renders every variant and writes design/components.json', () => {
    const components = MATRIX.map((spec) => {
      const cells = combinations(spec.axes).map(({ variant, props }) => ({
        variant,
        props,
        trees: {
          light: treeFor('light', () => spec.sample(props)),
          dark: treeFor('dark', () => spec.sample(props)),
        },
      }));

      expect(cells.length).toBeGreaterThan(0);
      for (const cell of cells) {
        expect(cell.trees.light).not.toBeNull();
        expect(cell.trees.dark).not.toBeNull();
        // Both modes are engineered, not derived — identical output for a
        // component that paints a surface means a theme lookup was missed.
        expect(JSON.stringify(cell.trees.light)).not.toBe(JSON.stringify(cell.trees.dark));
      }

      return {
        component: spec.component,
        set: spec.set,
        axes: spec.axes.map((a) => ({
          property: a.property,
          prop: a.prop,
          values: Object.keys(a.values),
        })),
        notes: spec.note,
        variants: cells,
      };
    });

    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(OUT, JSON.stringify({ _generated: GENERATED, components }, null, 2) + '\n');
    expect(components.length).toBe(MATRIX.length);
  });
});
