/**
 * Write the Chart props reference to `lib/generated/chart-props.ts`.
 *
 * The extractor reads the registry source with `node:fs`, and `docs-markdown`
 * is reachable from client components — so the reference is resolved here, at
 * build time, and the app imports a plain string. Mirrors `icons:generate`.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chartPropsData, chartPropsMarkdown } from './chart-props';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'lib', 'generated', 'chart-props.ts');

async function main() {
  const markdown = chartPropsMarkdown();
  // A parser that stops matching emits empty tables and the build still passes,
  // so fail loudly here rather than shipping a page with no reference on it.
  if (!markdown.includes('### Chart.Bar')) {
    throw new Error('chart props extractor produced no tables — the source shape changed');
  }

  await mkdir(dirname(out), { recursive: true });
  const data = chartPropsData();
  await writeFile(
    out,
    '// AUTO-GENERATED by scripts/generate-chart-props.ts — do not edit by hand.\n' +
      'export type ChartPropDoc = {\n' +
      '  name: string;\n' +
      '  type: string;\n' +
      '  required: boolean;\n' +
      '  default?: string;\n' +
      '  description: string;\n' +
      '};\n\n' +
      'export type ChartPartDoc = {\n' +
      '  name: string;\n' +
      '  description: string;\n' +
      '  props: ChartPropDoc[];\n' +
      '};\n\n' +
      `export const CHART_PROPS_MD = ${JSON.stringify(markdown)};\n\n` +
      '/** The same reference as data — the rendered page is JSX, not markdown. */\n' +
      `export const CHART_PROPS: { title: string; displayTitle?: string; props: ChartPropDoc[]; parts: ChartPartDoc[] }[] = ${JSON.stringify(data, null, 2)};\n`,
    'utf8',
  );
  const rows = markdown.split('\n').filter((line) => line.startsWith('| `')).length;
  console.log(`generate-chart-props: ${rows} props`);
}

void main();
