/**
 * Arlo UI — Variables Sync
 *
 * Imports `design/tokens.figma.json` (generated by `npm run design:sync`) into
 * this file's local variable collections.
 *
 * Why a plugin and not the REST API: Figma's Variables *write* endpoints are
 * Enterprise-only. The Plugin API has no such restriction, so this is the
 * portable push path for Starter/Student/Pro plans.
 *
 * Matching is by collection name + variable name, so re-importing updates in
 * place and keeps variable IDs stable — existing component bindings survive.
 * Nothing is ever deleted; variables removed from code are reported as orphans
 * so a human can decide.
 */

figma.showUI(__html__, { width: 460, height: 520, themeColors: true });

figma.ui.onmessage = async (msg) => {
  if (msg.type !== 'import') return;
  try {
    const report = await importTokens(msg.payload, msg.dryRun);
    figma.ui.postMessage({ type: 'done', report: report });
  } catch (err) {
    figma.ui.postMessage({ type: 'error', message: (err && err.message) || String(err) });
  }
};

async function importTokens(payload, dryRun) {
  if (!payload || !Array.isArray(payload.collections)) {
    throw new Error('Not an Arlo UI token payload — expected a `collections` array.');
  }

  const report = {
    dryRun: !!dryRun,
    version: payload.version || 'unknown',
    collections: [],
    conflicts: [],
    orphans: [],
  };

  const existingCollections = await figma.variables.getLocalVariableCollectionsAsync();

  for (const spec of payload.collections) {
    const line = { name: spec.name, created: 0, updated: 0, unchanged: 0, modes: [] };

    let collection = existingCollections.find((c) => c.name === spec.name);
    if (!collection) {
      if (dryRun) {
        // Nothing to diff against, but still report what the real run would
        // add — otherwise a brand-new collection misleadingly previews as +0.
        line.willCreateCollection = true;
        line.created = spec.variables.length;
        line.modes = spec.modes.slice();
        report.collections.push(line);
        continue;
      }
      collection = figma.variables.createVariableCollection(spec.name);
    }

    // Ensure every mode in the spec exists. The first spec mode renames the
    // collection's default mode so we don't strand an empty "Mode 1".
    const modeIds = {};
    spec.modes.forEach((modeName, i) => {
      const found = collection.modes.find((m) => m.name === modeName);
      if (found) {
        modeIds[modeName] = found.modeId;
        return;
      }
      if (dryRun) return;
      if (i === 0 && collection.modes.length === 1) {
        collection.renameMode(collection.modes[0].modeId, modeName);
        modeIds[modeName] = collection.modes[0].modeId;
      } else {
        modeIds[modeName] = collection.addMode(modeName);
      }
    });
    line.modes = spec.modes.slice();

    const localVars = await figma.variables.getLocalVariablesAsync();
    const inCollection = localVars.filter((v) => v.variableCollectionId === collection.id);
    const byName = new Map(inCollection.map((v) => [v.name, v]));
    const seen = new Set();

    for (const variable of spec.variables) {
      seen.add(variable.name);
      let node = byName.get(variable.name);

      if (node && node.resolvedType !== variable.type) {
        // Figma cannot change a variable's type after creation.
        report.conflicts.push(
          spec.name +
            ' › ' +
            variable.name +
            ': exists as ' +
            node.resolvedType +
            ', code says ' +
            variable.type +
            '. Delete it in Figma, then re-import.',
        );
        continue;
      }

      if (!node) {
        if (dryRun) {
          line.created++;
          continue;
        }
        node = figma.variables.createVariable(variable.name, collection, variable.type);
      }

      let changed = false;
      for (const modeName of spec.modes) {
        const modeId = modeIds[modeName];
        if (!modeId) continue;
        const next = variable.valuesByMode[modeName];
        if (next === undefined) continue;
        if (!valuesEqual(node.valuesByMode[modeId], next)) {
          if (!dryRun) node.setValueForMode(modeId, next);
          changed = true;
        }
      }

      if (byName.has(variable.name)) {
        if (changed) line.updated++;
        else line.unchanged++;
      } else {
        line.created++;
      }
    }

    for (const existing of inCollection) {
      if (!seen.has(existing.name)) {
        report.orphans.push(spec.name + ' › ' + existing.name);
      }
    }

    report.collections.push(line);
  }

  return report;
}

/** Structural compare so a no-op import reports "unchanged" instead of churning. */
function valuesEqual(a, b) {
  if (a === b) return true;
  if (a === undefined || b === undefined || a === null || b === null) return false;
  if (typeof a === 'object' && typeof b === 'object') {
    if ('r' in a && 'r' in b) {
      return (
        near(a.r, b.r) &&
        near(a.g, b.g) &&
        near(a.b, b.b) &&
        near(a.a === undefined ? 1 : a.a, b.a === undefined ? 1 : b.a)
      );
    }
    return false;
  }
  if (typeof a === 'number' && typeof b === 'number') return near(a, b);
  return false;
}

const near = (x, y) => Math.abs(x - y) < 1e-6;
