/**
 * Keeps the Arlo UI skill's machine-readable references in sync with the
 * implementation. Writes:
 *
 *   - skills/references/tokens.json     (from @arloui/tokens)
 *   - skills/references/registry.json   (from the registry manifest)
 *   - skills/references/usage.md        (CLI usage cheat sheet)
 *
 * Hand-authored markdown (`tokens.md`, `components.md`, `platform-mapping.md`,
 * `SKILL.md`) is never touched — those are the design contract.
 *
 * CI runs this script and fails if `git diff --quiet` doesn't pass after, so
 * the implementation can never silently drift from what the agent reads.
 *
 * Override the destination with ARLOUI_SKILL_PATH (rarely needed):
 *   ARLOUI_SKILL_PATH=skills npm run skill:sync
 */
import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { raw } from '../packages/tokens/src/raw';
import { REGISTRY } from '../packages/registry/src/manifest';

const ROOT = resolve(fileURLToPath(import.meta.url), '../..');
const SKILL_PATH = resolve(
  ROOT,
  process.env.ARLOUI_SKILL_PATH ?? 'skills',
);
const REFS = join(SKILL_PATH, 'references');

const HEADER =
  '// AUTO-GENERATED by scripts/sync-skill.ts. Do not edit by hand.\n' +
  '// Regenerate with `npm run skill:sync`.';

async function main() {
  if (!existsSync(SKILL_PATH)) {
    console.error(
      `skill folder not found at ${SKILL_PATH}.\n` +
        `Set ARLOUI_SKILL_PATH or check that skills/ exists (SKILL.md + references/).`,
    );
    process.exit(1);
  }

  await mkdir(REFS, { recursive: true });

  await writeFile(
    join(REFS, 'tokens.json'),
    JSON.stringify({ _generated: HEADER, ...raw }, null, 2) + '\n',
  );

  const manifest = {
    _generated: HEADER,
    version: REGISTRY.version,
    items: REGISTRY.items.map((it) => ({
      name: it.name,
      kind: it.kind,
      title: it.title,
      description: it.description,
      registryDependencies: it.registryDependencies ?? [],
      dependencies: it.dependencies ?? [],
      tags: it.meta?.tags ?? [],
      figma: it.meta?.figma,
    })),
  };
  await writeFile(
    join(REFS, 'registry.json'),
    JSON.stringify(manifest, null, 2) + '\n',
  );

  const usage = renderUsageMd(manifest);
  await writeFile(join(REFS, 'usage.md'), usage);

  console.log('synced:');
  console.log(`  · ${join(REFS, 'tokens.json')}`);
  console.log(`  · ${join(REFS, 'registry.json')}`);
  console.log(`  · ${join(REFS, 'usage.md')}`);
}

function renderUsageMd(manifest: {
  items: Array<{ name: string; title: string; description: string; kind: string }>;
}) {
  const lines: string[] = [];
  lines.push(
    '<!-- AUTO-GENERATED by scripts/sync-skill.ts. Do not edit by hand. Regenerate with `npm run skill:sync`. -->',
  );
  lines.push('');
  lines.push('# Using Arlo UI Registry Components');
  lines.push('');
  lines.push(
    'When implementing a component that already exists in the Arlo UI registry, **use the CLI to copy it in** rather than rewriting it. This keeps the design system consistent and lets the user inherit upstream improvements via `arloui diff`.',
  );
  lines.push('');
  lines.push('## CLI');
  lines.push('');
  lines.push('```bash');
  lines.push('# one-time setup (writes arlo.json + tokens + ThemeProvider)');
  lines.push('npx arloui init');
  lines.push('');
  lines.push('# add a component');
  lines.push('npx arloui add button');
  lines.push('');
  lines.push('# multiple at once');
  lines.push('npx arloui add button card');
  lines.push('');
  lines.push('# list everything available');
  lines.push('npx arloui list');
  lines.push('');
  lines.push('# check whether a local component drifted from the registry');
  lines.push('npx arloui diff button');
  lines.push('```');
  lines.push('');
  lines.push('## Available components');
  lines.push('');
  const byKind: Record<string, typeof manifest.items> = {};
  for (const it of manifest.items) (byKind[it.kind] ??= []).push(it);
  for (const kind of ['foundation', 'primitive', 'pattern', 'icon']) {
    const items = byKind[kind];
    if (!items?.length) continue;
    lines.push(`### ${kind}`);
    lines.push('');
    for (const it of items) {
      lines.push(`- **${it.name}** — ${it.title}. ${it.description}`);
    }
    lines.push('');
  }
  lines.push('## Decision rule');
  lines.push('');
  lines.push('1. Need a component listed above? → `npx arloui add <name>`. Do not rewrite.');
  lines.push(
    '2. Need a variant of a listed component? → run `arloui add` to bring it in, then customize the local copy. Document the customization in the component file.',
  );
  lines.push(
    '3. Building something genuinely new? → follow the design rules in `tokens.md` and `components.md`, then propose contributing it back to the registry.',
  );
  lines.push('');
  return lines.join('\n');
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
