/**
 * Emits design-tool-shaped token payloads from `@arloui/tokens`.
 *
 * Code is the source of truth; design tools are downstream consumers. This
 * script never reads from Figma or Paper — it only writes:
 *
 *   - tokens.figma.json   Figma variable collections (imported by the
 *                                `tooling/figma-variables-sync` plugin — the
 *                                Variables REST *write* API is Enterprise-only,
 *                                so the push is a one-click plugin action).
 *   - tokens.paper.json   Paper design tokens, ordered for `create_tokens`
 *                                (palette first, semantic aliases second).
 *
 * Naming follows the conventions already established in the Arlo UI v1.0 Figma
 * library — kebab-case leaf names, slash-separated groups:
 *
 *   COLOR - PRIMITIVES          Grey/500, Primary/600, Alpha Black/40
 *   COLOR - SEMANTIC            Surfaces & Backgrounds/surface-background
 *   SPACING                     space-4
 *   SIZING - COMPONENT SPECIFIC Button Heights/button-md
 *   RADIUS                      radius-lg            (new — not yet in Figma)
 *   TYPOGRAPHY                  Font Size/body-large (new — not yet in Figma)
 *
 * CI runs this and fails if `git diff --quiet` doesn't pass afterwards, so the
 * emitted payloads can never silently drift from the implementation.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { raw } from '../packages/tokens/src/raw';

const ROOT = resolve(fileURLToPath(import.meta.url), '../..');
const OUT = join(ROOT, 'tooling', 'figma-variables-sync');

const GENERATED =
  'AUTO-GENERATED by scripts/sync-design.ts. Do not edit by hand. Regenerate with `npm run design:sync`.';

/* ------------------------------------------------------------------ colors */

type Rgba = { r: number; g: number; b: number; a: number };

/**
 * Parse the colour forms that appear in `@arloui/tokens`: `#RGB`, `#RRGGBB`,
 * `#RRGGBBAA`, `rgba(r, g, b, a)`, and the keyword `transparent`.
 * Channels come back 0–1, which is what the Figma Plugin API wants.
 */
function parseColor(input: string): Rgba {
  const value = input.trim();

  if (value === 'transparent') return { r: 0, g: 0, b: 0, a: 0 };

  if (value.startsWith('#')) {
    let hex = value.slice(1);
    if (hex.length === 3) hex = hex.replace(/./g, (c) => c + c);
    if (hex.length !== 6 && hex.length !== 8) {
      throw new Error(`Unparseable hex colour: ${input}`);
    }
    const int = Number.parseInt(hex, 16);
    const hasAlpha = hex.length === 8;
    return {
      r: ((int >>> (hasAlpha ? 24 : 16)) & 0xff) / 255,
      g: ((int >>> (hasAlpha ? 16 : 8)) & 0xff) / 255,
      b: ((int >>> (hasAlpha ? 8 : 0)) & 0xff) / 255,
      a: hasAlpha ? (int & 0xff) / 255 : 1,
    };
  }

  const rgba = value.match(
    /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/i,
  );
  if (rgba) {
    return {
      r: Number(rgba[1]) / 255,
      g: Number(rgba[2]) / 255,
      b: Number(rgba[3]) / 255,
      a: rgba[4] === undefined ? 1 : Number(rgba[4]),
    };
  }

  throw new Error(`Unparseable colour: ${input}`);
}

/** Round-trip a token colour back to a CSS string, preserving alpha. */
function toCss(input: string): string {
  const { r, g, b, a } = parseColor(input);
  const ch = (n: number) => Math.round(n * 255);
  return a === 1
    ? `#${[r, g, b].map((n) => ch(n).toString(16).padStart(2, '0')).join('').toUpperCase()}`
    : `rgba(${ch(r)}, ${ch(g)}, ${ch(b)}, ${Number(a.toFixed(4))})`;
}

/* ------------------------------------------------------------------- names */

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const titleCase = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

/**
 * Which Figma group a semantic colour belongs to.
 *
 * These are transcribed from the live Arlo UI v1.0 library, not invented — an
 * import only updates in place if the full `Group/leaf` path matches exactly.
 * Note the shape of the real taxonomy: focus-ring and touch-feedback do *not*
 * get their own groups, they live under Interactive Elements; and
 * `pull-indicator` sits alone under Gestures rather than with the nav tokens.
 *
 * `Data Visualization` is the one exception: it has no counterpart in the
 * library yet, because the chart colours were added in code and never mirrored
 * across. The first import will *create* the group rather than update it, which
 * is the intended outcome — components already reach for `chartPositive` and
 * friends, and a token a component uses but the canvas lacks is a value a
 * designer has to hardcode. Rename it here if the library ends up calling it
 * something else, or the next import will make a second group beside it.
 */
const SEMANTIC_GROUPS: Array<[RegExp, string]> = [
  [/^(surface|bg)/, 'Surfaces & Backgrounds'],
  [/^text/, 'Text & Content'],
  [/^(interactive|focusRing|touchFeedback|accent)/, 'Interactive Elements'],
  [/^border/, 'Borders & Dividers'],
  [/^(feedback|success|warning|danger)/, 'Feedback States'],
  [/^nav/, 'Navigation & UI Chrome'],
  [/^pull/, 'Gestures'],
  [/^chart/, 'Data Visualization'],
];

/** Leaf names the library spells differently from plain kebab-case. */
const SEMANTIC_LEAF_OVERRIDES: Record<string, string> = {
  focusRingMain: 'Focus-ring-main',
  focusRingError: 'Focus-ring-error',
};

function semanticGroup(name: string): string {
  const hit = SEMANTIC_GROUPS.find(([re]) => re.test(name));
  if (!hit) throw new Error(`No Figma group mapped for semantic colour "${name}"`);
  return hit[1];
}

const semanticLeaf = (name: string) => SEMANTIC_LEAF_OVERRIDES[name] ?? kebab(name);

/**
 * Variables that exist in Figma on purpose and have no code counterpart.
 *
 * Declared so the import plugin can filter them out of its orphan report — an
 * orphan that is *not* listed here means something actually drifted, which is
 * only a useful signal if the expected ones are named.
 */
const FIGMA_ONLY: Array<{ collection: string; name: string; why: string }> = [
  {
    collection: 'COLOR - PRIMITIVES',
    name: 'Alpha Black/alpha-black-5',
    why: 'Figma-side step with no equivalent in the alphaRamp scale.',
  },
];

/* ----------------------------------------------------------- figma payload */

type FigmaVariable =
  | { name: string; type: 'COLOR'; valuesByMode: Record<string, Rgba> }
  | { name: string; type: 'FLOAT'; valuesByMode: Record<string, number> }
  | { name: string; type: 'STRING'; valuesByMode: Record<string, string> };

type FigmaCollection = {
  name: string;
  modes: string[];
  variables: FigmaVariable[];
};

const color = (name: string, valuesByMode: Record<string, string>): FigmaVariable => ({
  name,
  type: 'COLOR',
  valuesByMode: Object.fromEntries(
    Object.entries(valuesByMode).map(([mode, v]) => [mode, parseColor(v)]),
  ),
});
const float = (name: string, value: number): FigmaVariable => ({
  name,
  type: 'FLOAT',
  valuesByMode: { Value: value },
});
const string = (name: string, value: string): FigmaVariable => ({
  name,
  type: 'STRING',
  valuesByMode: { Value: value },
});

function buildFigma(): FigmaCollection[] {
  const { paletteMain, paletteSecondary, alphaRamp, semantic } = raw.color;

  /* COLOR - PRIMITIVES ------------------------------------------------- */
  const primitives: FigmaVariable[] = [];

  for (const [name, hex] of Object.entries(paletteMain.base)) {
    primitives.push(color(`Base/${titleCase(name)}`, { Value: hex }));
  }
  for (const [family, ramp] of Object.entries(paletteMain)) {
    if (family === 'base') continue;
    for (const [step, hex] of Object.entries(ramp as Record<string, string>)) {
      primitives.push(color(`${titleCase(family)}/${step}`, { Value: hex }));
    }
  }
  for (const [family, ramp] of Object.entries(paletteSecondary)) {
    for (const [step, hex] of Object.entries(ramp as Record<string, string>)) {
      primitives.push(color(`${titleCase(family)}/${step}`, { Value: hex }));
    }
  }
  // alphaRamp exposes `white`/`black` ramps plus `whiteBase`/`blackBase` scalars.
  // The library repeats the group in the leaf name (`Alpha White/alpha-white-40`),
  // unlike the numeric ramps above (`Grey/500`) — match it or every alpha token
  // imports as a duplicate.
  for (const tone of ['white', 'black'] as const) {
    const ramp = alphaRamp[tone] as Record<string, string>;
    for (const [step, value] of Object.entries(ramp)) {
      primitives.push(
        color(`Alpha ${titleCase(tone)}/alpha-${tone}-${step}`, { Value: value }),
      );
    }
  }

  /* COLOR - SEMANTIC --------------------------------------------------- */
  // `semantic.*` is the Figma-derived utility table; `raw.color.light/dark` adds
  // the flat aliases components actually reach for (`surfaceRaised`, `borderStrong`,
  // `accent`, …). Both must ship — a token a component uses but the canvas lacks
  // is a value a designer has to hardcode, which is how systems come apart.
  const semanticNames = [
    ...Object.keys(semantic.light),
    ...Object.keys(raw.color.light).filter((k) => !(k in semantic.light)),
  ];
  const semanticVars: FigmaVariable[] = semanticNames.map((name) =>
    color(`${semanticGroup(name)}/${semanticLeaf(name)}`, {
      Light: (raw.color.light as Record<string, string>)[name],
      Dark: (raw.color.dark as Record<string, string>)[name],
    }),
  );

  /* SPACING / RADIUS / SIZING ------------------------------------------ */
  const spacingVars = Object.entries(raw.spacing).map(([step, px]) =>
    float(`space-${step}`, px as number),
  );

  const radiusVars = Object.entries(raw.radii).map(([name, px]) =>
    float(`radius-${name}`, px as number),
  );

  // Transcribed from the live library. `touchTarget` has no counterpart there
  // yet, so its group name is the one guess in this map — it will import as new.
  const sizingGroups: Record<string, string> = {
    icon: 'Icons',
    avatar: 'Avatars',
    buttonHeight: 'Button Heights',
    touchTarget: 'Touch Targets',
  };
  const sizingLeaf: Record<string, string> = {
    icon: 'icon',
    avatar: 'avatar',
    buttonHeight: 'button',
    touchTarget: 'touch-target',
  };
  const sizingVars: FigmaVariable[] = [];
  for (const [group, scale] of Object.entries(raw.sizing)) {
    for (const [step, px] of Object.entries(scale as Record<string, number>)) {
      sizingVars.push(float(`${sizingGroups[group]}/${sizingLeaf[group]}-${kebab(step)}`, px));
    }
  }

  /* TYPOGRAPHY ---------------------------------------------------------- */
  const typographyVars: FigmaVariable[] = [];
  for (const [name, family] of Object.entries(raw.typography.fontFamilies)) {
    typographyVars.push(string(`Font Family/${kebab(name)}`, family as string));
  }
  for (const [name, weight] of Object.entries(raw.typography.fontWeights)) {
    typographyVars.push(string(`Font Weight/${kebab(name)}`, String(weight)));
  }
  for (const [name, spec] of Object.entries(raw.typography.scale)) {
    const s = spec as { fontSize: number; lineHeight: number; letterSpacing?: number };
    const leaf = kebab(name);
    typographyVars.push(float(`Font Size/${leaf}`, s.fontSize));
    typographyVars.push(float(`Line Height/${leaf}`, s.lineHeight));
    if (typeof s.letterSpacing === 'number') {
      typographyVars.push(float(`Letter Spacing/${leaf}`, s.letterSpacing));
    }
  }

  return [
    { name: 'COLOR - PRIMITIVES', modes: ['Value'], variables: primitives },
    { name: 'COLOR - SEMANTIC', modes: ['Light', 'Dark'], variables: semanticVars },
    { name: 'SPACING', modes: ['Value'], variables: spacingVars },
    { name: 'BORDER RADIUS', modes: ['Value'], variables: radiusVars },
    { name: 'SIZING - COMPONENT SPECIFIC', modes: ['Value'], variables: sizingVars },
    { name: 'TYPOGRAPHY', modes: ['Value'], variables: typographyVars },
  ];
}

/* ----------------------------------------------------------- paper payload */

type PaperTokenType =
  | 'color'
  | 'spacing'
  | 'radius'
  | 'fontFamily'
  | 'fontSize'
  | 'fontWeight'
  | 'letterSpacing'
  | 'lineHeight';

type PaperToken = {
  type: PaperTokenType;
  /** Full CSS custom property name — Paper's `create_tokens` requires `--…`. */
  name: string;
  value: string;
  description?: string;
};

/** Paper's namespace per token type (Tailwind v4 `@theme` convention). */
const PAPER_PREFIX: Record<PaperTokenType, string> = {
  color: '--color-',
  spacing: '--spacing-',
  radius: '--radius-',
  fontFamily: '--font-',
  fontSize: '--text-',
  fontWeight: '--font-weight-',
  letterSpacing: '--tracking-',
  lineHeight: '--leading-',
};

/**
 * Paper holds one value per token (no modes), so the light semantic set becomes
 * the canonical `--color-*` names and dark ships alongside as `--color-dark-*`.
 * Semantic tokens alias the palette via `var(--color-…)` wherever the underlying
 * value matches a palette entry exactly, which preserves the palette → semantic
 * relationship that `packages/tokens` encodes.
 */
function buildPaper(): PaperToken[] {
  const { paletteMain, paletteSecondary, alphaRamp, semantic } = raw.color;
  const tokens: PaperToken[] = [];
  const push = (type: PaperTokenType, name: string, value: string, description?: string) =>
    tokens.push({ type, name: PAPER_PREFIX[type] + name, value, ...(description ? { description } : {}) });

  /** css value -> palette custom-property name, for aliasing. */
  const paletteIndex = new Map<string, string>();
  const addPalette = (name: string, value: string, description: string) => {
    const css = toCss(value);
    push('color', name, css, description);
    if (!paletteIndex.has(css)) paletteIndex.set(css, PAPER_PREFIX.color + name);
  };

  // Neutrals first, then primary, then status, then secondary families —
  // the ordering `create_tokens` asks for.
  addPalette('white', paletteMain.base.white, 'Palette · base');
  addPalette('black', paletteMain.base.black, 'Palette · base');
  for (const family of ['grey', 'primary', 'success', 'warning', 'error'] as const) {
    for (const [step, hex] of Object.entries(paletteMain[family] as Record<string, string>)) {
      addPalette(`${family}-${step}`, hex, `Palette · ${family}`);
    }
  }
  for (const [family, ramp] of Object.entries(paletteSecondary)) {
    for (const [step, hex] of Object.entries(ramp as Record<string, string>)) {
      addPalette(`${kebab(family)}-${step}`, hex, `Palette · secondary · ${family}`);
    }
  }
  for (const tone of ['white', 'black'] as const) {
    for (const [step, value] of Object.entries(alphaRamp[tone] as Record<string, string>)) {
      addPalette(`alpha-${tone}-${step}`, value, `Palette · alpha ${tone}`);
    }
  }

  const alias = (value: string) => {
    const css = toCss(value);
    const hit = paletteIndex.get(css);
    return hit ? `var(${hit})` : css;
  };

  // Same superset as the Figma payload: the utility table plus the flat aliases
  // components reference directly.
  const semanticNames = [
    ...Object.keys(semantic.light),
    ...Object.keys(raw.color.light).filter((k) => !(k in semantic.light)),
  ];
  for (const name of semanticNames) {
    push('color', kebab(name), alias((raw.color.light as Record<string, string>)[name]), 'Semantic · light');
  }
  for (const name of semanticNames) {
    push('color', `dark-${kebab(name)}`, alias((raw.color.dark as Record<string, string>)[name]), 'Semantic · dark');
  }

  for (const [step, px] of Object.entries(raw.spacing)) {
    push('spacing', step, `${px}px`);
  }
  for (const [name, px] of Object.entries(raw.radii)) {
    push('radius', name, `${px}px`);
  }
  for (const [name, family] of Object.entries(raw.typography.fontFamilies)) {
    push('fontFamily', name, family as string);
  }
  for (const [name, weight] of Object.entries(raw.typography.fontWeights)) {
    push('fontWeight', kebab(name), String(weight));
  }
  for (const [name, spec] of Object.entries(raw.typography.scale)) {
    const s = spec as { fontSize: number; lineHeight: number; letterSpacing?: number };
    const leaf = kebab(name);
    push('fontSize', leaf, `${s.fontSize}px`);
    push('lineHeight', leaf, `${s.lineHeight}px`);
    if (typeof s.letterSpacing === 'number') {
      // Token letter-spacing is authored in px against its own font size; Paper
      // prefers em so the value survives a type-scale change.
      const em = Number((s.letterSpacing / s.fontSize).toFixed(4));
      push('letterSpacing', leaf, `${em}em`);
    }
  }

  return tokens;
}

/* -------------------------------------------------------------------- main */

async function main() {
  await mkdir(OUT, { recursive: true });

  const collections = buildFigma();
  const paper = buildPaper();

  await writeFile(
    join(OUT, 'tokens.figma.json'),
    JSON.stringify(
      { _generated: GENERATED, version: raw.version, figmaOnly: FIGMA_ONLY, collections },
      null,
      2,
    ) + '\n',
  );
  await writeFile(
    join(OUT, 'tokens.paper.json'),
    JSON.stringify({ _generated: GENERATED, version: raw.version, tokens: paper }, null, 2) +
      '\n',
  );

  const varCount = collections.reduce((n, c) => n + c.variables.length, 0);
  console.log('synced design payloads:');
  for (const c of collections) {
    console.log(`  · ${c.name} — ${c.variables.length} variables (${c.modes.join(', ')})`);
  }
  console.log(`  → tooling/figma-variables-sync/tokens.figma.json  ${varCount} variables`);
  console.log(`  → tooling/figma-variables-sync/tokens.paper.json  ${paper.length} tokens`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
